<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * The 9 logos that were hardcoded in the homepage "شركاؤنا" carousel
     * before it became admin-managed. Seeded here (not only via db:seed,
     * following the advertisement_slots migration's precedent) so a bare
     * `php artisan migrate` leaves the carousel looking exactly as it did
     * before this change — admins can then edit/add/remove/reorder from
     * Filament (المحتوى → شعارات الشركاء) going forward. The matching image
     * files are copied into storage/app/public/partner-logos/ alongside
     * this migration, not generated by it.
     *
     * @var array<int, array{name: string, file: string}>
     */
    public static array $seed = [
        ['name' => 'أساس', 'file' => 'asas.png'],
        ['name' => 'خليج الزجاج', 'file' => 'gulf-glass.png'],
        ['name' => 'لمسة', 'file' => 'lamsa.png'],
        ['name' => 'مانع', 'file' => 'manea.png'],
        ['name' => 'مداد', 'file' => 'midad.png'],
        ['name' => 'نوران', 'file' => 'noran.png'],
        ['name' => 'عمران ستيل', 'file' => 'omran-steel.png'],
        ['name' => 'روافع', 'file' => 'rawafea.png'],
        ['name' => 'صبا', 'file' => 'sabba.png'],
    ];

    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('partner_logos', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('logo');
            $table->boolean('is_active')->default(true);
            $table->unsignedInteger('sort_order')->default(0);
            $table->timestamps();
        });

        $now = now();

        foreach (self::$seed as $i => $row) {
            DB::table('partner_logos')->updateOrInsert(
                ['name' => $row['name']],
                [
                    'logo' => 'partner-logos/'.$row['file'],
                    'is_active' => true,
                    'sort_order' => ($i + 1) * 10,
                    'updated_at' => $now,
                    'created_at' => $now,
                ]
            );
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('partner_logos');
    }
};
